### ISSUE TITLE
Mutify does not work when phone is locked

### ISSUE THREAD

**Issue by amksde** [teekamsuthar/Mutify#7]
I am currently using Mutify on my Samsung M40 device running Android 11.  Whenever I start using Mutify, it works perfectly, but when the phone is locked (manually or because of screen timeout), Mutify somehow cannot detect ads on Spotify, and therefore does not block them. And **as soon as** I unlock my phone (that is open the screen) ads start getting muted. It is very annoying when I am trying to use my device hands-free. Please try to resolve it.

**Comment by teekamsuthar** [comment]
Hi @Professor-Of-Stupidity, Thanks for reporting, we're aware of this issue happening in Samsung devices specifically. Samsung devices are really aggressive in killing apps running in the background. We're already working on the fix and it would be rolled out in the next update of Mutify. However, for the time being you can follow the steps mentioned at https://dontkillmyapp.com/samsung which will make sure Mutify works uninterruptedly even after device is locked. :)

Thanks again,
Teekam
